# This is a basic workflow to help you get started with Actions

name: JP Checker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: First Setup
        run: |
         sudo chmod +x ./jp/first-setup.sh
         sudo bash -x ./jp/first-setup.sh actions

      # Runs a set of commands using the runners shell
      - name: Second Setup
        run: |
         sudo chmod +x ./jp/second-setup.sh
         sudo bash -x ./jp/second-setup.sh

      # Runs a set of commands using the runners shell
      - name: Custom Setup
        run: |
         sudo chmod +x ./jp/customize-setup.sh
         sudo bash -x ./jp/customize-setup.sh 192.168.0.1 01 wifi 192.168.0.1 192.168.0.1
